version: '3.9'

services:
  django_gunicorn:
    build: .
    expose:
      - "8000"
    volumes:
      - static_volume:/app/static  # static 파일 볼륨
      # - media_volume:/app/media  # media 파일 볼륨 (필요 시)

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./resources/nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx 설정 파일을 컨테이너에 연결
      - static_volume:/app/static  # Django에서 수집된 static 파일
      # - media_volume:/app/media  # Django에서 사용하는 media 파일 (필요 시)
      - ./resources/cert/localhost.pem:/etc/nginx/ssl/localhost.pem
      - ./resources/cert/localhost-key.pem:/etc/nginx/ssl/localhost-key.pem
    depends_on:
      - django_gunicorn

volumes:
  static_volume:
  # media_volume: