# Generated by Django 5.1.1 on 2024-09-13 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistorys",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transaction_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("transfer", "Transfer"),
                            ("auto_transfer", "Auto Transfer"),
                            ("card_payment", "Card Payment"),
                        ],
                        max_length=15,
                    ),
                ),
                ("balance_after_transaction", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "deposit_withdrawal_type",
                    models.CharField(choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")], max_length=15),
                ),
                ("transaction_description", models.CharField(max_length=255)),
                ("transaction_date", models.DateField(auto_now_add=True)),
                ("transaction_time", models.TimeField(auto_now_add=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.accounts")),
            ],
        ),
    ]
