# Generated by Django 5.1.1 on 2024-09-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone_number",
            field=models.IntegerField(blank=True),
        ),
    ]
