# Generated by Django 5.1.1 on 2024-09-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_users_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
