# Generated by Django 5.1.1 on 2024-09-17 15:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_number", models.CharField(max_length=50, unique=True)),
                (
                    "bank_code",
                    models.CharField(
                        choices=[
                            ("kakao", "Kakao Bank"),
                            ("kb", "KB Kookmin Bank"),
                            ("nh", "NH NongHyup Bank"),
                            ("ibk", "IBK Industrial Bank of Korea"),
                            ("sh", "ShinHan Bank"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings Account"),
                            ("checking", "Checking Account"),
                            ("loan", "Loan Account"),
                            ("overdraft", "Overdraft Account"),
                        ],
                        max_length=50,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
